<?php
declare(strict_types=1);

namespace CrudForge\Generators;

use CrudForge\IO\Filesystem;

final class CrudGenerator
{
    public function __construct(private Filesystem $fs = new Filesystem()) {}
    
    public function generate(string $modelName): void
    {
        $studly = $this->toStudly($modelName);
        $snake = $this->toSnake($modelName);
        $basePath = getcwd() . '/generated';
        
        $this->fs->ensureDir("{$basePath}/Models");
        $this->fs->ensureDir("{$basePath}/Controllers");
        
        $this->fs->put(
            "{$basePath}/Models/{$studly}.php",
            $this->generateModel($studly)
        );
        
        $this->fs->put(
            "{$basePath}/Controllers/{$studly}Controller.php",
            $this->generateController($studly)
        );
        
        echo "📦 {$studly} Model & Controller created!\n";
    }
    
    private function generateModel(string $studly): string
    {
        return "<?php\nclass {$studly} {\n    // Generated by CrudForge\n}";
    }
    
    private function generateController(string $studly): string
    {
        return "<?php\nclass {$studly}Controller {\n    public function index() {}\n    public function store() {}\n}";
    }
    
    private function toStudly(string $name): string
    {
        return ucfirst(str_replace(' ', '', ucwords(str_replace(['-', '_'], ' ', strtolower($name)))));
    }
    
    private function toSnake(string $name): string
    {
        return strtolower(preg_replace('/(?<!^)[A-Z]/', '_$0', $name));
    }
}
